site_name: Sawblade Wiki
site_url: https://sawblade-entertainment.github.io/SawbladeWiki/
repo_url: https://github.com/Sawblade-Entertainment/SawbladeWiki
theme:
  name: terminal
  palette: dark
  features:
    - footer.prev_next
    - revision.date
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Backrooms 1999:
    - Wiki: 'Backrooms 1999/index.md'
    - Developer Log: 'Backrooms 1999/devlog.md'
plugins:
  - git-revision-date
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true